# Generated by Django 4.2.4 on 2023-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=500)),
                ('prix', models.IntegerField()),
                ('quantite', models.IntegerField()),
            ],
        ),
    ]
